<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '9fa3eefe947cd3abb9b93c9fc7b32f8d5862ca77',
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '9fa3eefe947cd3abb9b93c9fc7b32f8d5862ca77',
            'dev_requirement' => false,
        ),
        'chillerlan/php-qrcode' => array(
            'pretty_version' => '4.3.2',
            'version' => '4.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-qrcode',
            'aliases' => array(),
            'reference' => 'b625396e0752d79747a55205ae7e191eeb459dcd',
            'dev_requirement' => false,
        ),
        'chillerlan/php-settings-container' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-settings-container',
            'aliases' => array(),
            'reference' => 'ec834493a88682dd69652a1eeaf462789ed0c5f5',
            'dev_requirement' => false,
        ),
        'salla/zatca' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../salla/zatca',
            'aliases' => array(),
            'reference' => '3c1f534acf16a06687102895b511ffe4f74a7af1',
            'dev_requirement' => false,
        ),
    ),
);
